language: chsarp
script:
  - xbuild /p:Configuration=Debug CiCdTestApp.sln
before_install:
  - sudo apt-get install nunit-console
before_script:
  - nuget restore CiCdTestApp.sln
after_script:
  - nunit-console CiCdTestApp.Tests/bin/Debug/CiCdTestApp.Tests.dll